import { describe, expect, test } from "vitest";
import {
  autoGenerateDays,
  MAX_CONCURRENT_GENERATIONS,
} from "@/server/insights/auto-generate";

/**
 * Auto-generation, and the rule it is most likely to break.
 *
 * A page-load batch looks like a loading concern. It is a permission one: a
 * manager opening a month sees thirty day cells, and a guard that lives in the
 * cell rather than in the batch buys thirty insights nobody asked for.
 */

/** Records how many generations were running at once. */
function tracker(delayMs = 5) {
  let inFlight = 0;
  let peak = 0;
  const seen: string[] = [];
  return {
    peak: () => peak,
    seen: () => seen,
    generate: async (date: string) => {
      seen.push(date);
      inFlight += 1;
      peak = Math.max(peak, inFlight);
      await new Promise((r) => setTimeout(r, delayMs));
      inFlight -= 1;
    },
  };
}

const TEN = Array.from({ length: 10 }, (_, i) => `2026-09-${String(i + 1).padStart(2, "0")}`);
const THIRTY = Array.from({ length: 30 }, (_, i) => `2026-09-${String(i + 1).padStart(2, "0")}`);

describe("13. ten uncached dates fire ten extractions, at most three at once", () => {
  test("every date is generated", async () => {
    const t = tracker();
    const report = await autoGenerateDays({
      viewerRole: "INSTRUCTOR",
      staleDates: TEN,
      generate: t.generate,
    });
    expect(report.attempted).toHaveLength(10);
    expect(new Set(t.seen())).toEqual(new Set(TEN));
  });

  test("and never more than three are in flight", async () => {
    const t = tracker();
    const report = await autoGenerateDays({
      viewerRole: "INSTRUCTOR",
      staleDates: TEN,
      generate: t.generate,
    });
    // Measured on both sides: the limiter's own count and the work's.
    expect(t.peak()).toBeLessThanOrEqual(MAX_CONCURRENT_GENERATIONS);
    expect(report.peakConcurrency).toBeLessThanOrEqual(MAX_CONCURRENT_GENERATIONS);
    /* And it really does run them in parallel — a serial implementation would
       also satisfy "at most three" while taking ten times as long. */
    expect(t.peak()).toBe(MAX_CONCURRENT_GENERATIONS);
  });

  test("one failed day does not abandon the rest", async () => {
    let calls = 0;
    const report = await autoGenerateDays({
      viewerRole: "INSTRUCTOR",
      staleDates: TEN,
      generate: async (date) => {
        calls += 1;
        if (date === TEN[3]) throw new Error("provider said no");
      },
    });
    expect(calls, "the queue continues past a failure").toBe(10);
    expect(report.attempted).toHaveLength(10);
  });
});

describe("14. a manager loading a thirty-day range fires zero extraction calls", () => {
  test("nothing is generated, and the reason is the permission", async () => {
    /* THE operational test. This is the rule that costs real money when it
       breaks, and the batch path is where it breaks. */
    const t = tracker();
    const report = await autoGenerateDays({
      viewerRole: "MANAGER",
      staleDates: THIRTY,
      generate: t.generate,
    });

    expect(t.seen(), "a manager's page load must buy nothing").toEqual([]);
    expect(report.attempted).toEqual([]);
    expect(report.skipped).toBe("not-permitted");
    expect(report.peakConcurrency).toBe(0);
  });

  test("an admin is a manager here — more authority to read is not to spend", async () => {
    const t = tracker();
    const report = await autoGenerateDays({
      viewerRole: "ADMIN",
      staleDates: THIRTY,
      generate: t.generate,
    });
    expect(t.seen()).toEqual([]);
    expect(report.skipped).toBe("not-permitted");
  });

  test("the same thirty dates DO generate for the instructor whose days they are", async () => {
    /* The mirror, so the test above is known to be measuring the permission
       rather than an empty queue or a broken fake. */
    const t = tracker(1);
    const report = await autoGenerateDays({
      viewerRole: "INSTRUCTOR",
      staleDates: THIRTY,
      generate: t.generate,
    });
    expect(report.attempted).toHaveLength(30);
    expect(t.peak()).toBe(MAX_CONCURRENT_GENERATIONS);
  });
});

describe("nothing stale is not the same as not permitted", () => {
  test("an instructor with every cell cached makes no calls, and says why", async () => {
    const t = tracker();
    const report = await autoGenerateDays({
      viewerRole: "INSTRUCTOR",
      staleDates: [],
      generate: t.generate,
    });
    expect(t.seen()).toEqual([]);
    expect(report.skipped, "distinguishable from the manager case").toBe("nothing-stale");
  });
});
