/**
 * Filling a view's day cells without anybody clicking anything.
 *
 * ── The rule this file exists to keep ─────────────────────────────────────
 * Auto-generation is exactly where a permission gets broken by accident,
 * because a page-load batch looks like a LOADING concern rather than a
 * PERMISSION one. The generation matrix says a manager's day view is READ_ONLY;
 * a batch that fills thirty cells on scroll can walk straight past a guard that
 * lives in the cell, and buy thirty insights the manager never asked for.
 *
 * So the role is checked here, once, before any date is considered — not per
 * cell, and not by the caller. A manager opening a month makes zero calls and
 * sees Pending in every uncached cell.
 *
 * ── Why bounded ──────────────────────────────────────────────────────────
 * Thirty uncached days is thirty provider calls. Unbounded, they arrive
 * together, and the provider answers some of them with a 503 that costs the
 * same as a success. Three at a time keeps a month's worth of generation to a
 * queue the provider will actually serve, and lets results stream into cells as
 * they arrive rather than after the slowest.
 */
import { generationModeFor, type ViewerRole } from "./access";

/** The most calls in flight at once, for the reason above. */
export const MAX_CONCURRENT_GENERATIONS = 3;

export type AutoGenerateReport = {
  /** Dates a generation was actually started for. */
  attempted: string[];
  /** Why nothing was attempted, when nothing was. */
  skipped: "not-permitted" | "nothing-stale" | null;
  /** The high-water mark of concurrent calls, so "at most three" is measured. */
  peakConcurrency: number;
};

/**
 * Run `generate` over `dates`, at most {@link MAX_CONCURRENT_GENERATIONS} at a
 * time, and never at all for a viewer who may not generate this scope.
 *
 * Failures are swallowed deliberately: this is a background fill for cells that
 * already have a correct thing to render without it. A day whose generation
 * fails stays Pending, which is what it was a moment ago.
 */
export async function autoGenerateDays(input: {
  viewerRole: ViewerRole;
  /** Visible dates that hold a worklog row and no valid cached insight. */
  staleDates: readonly string[];
  generate: (date: string) => Promise<unknown>;
}): Promise<AutoGenerateReport> {
  /* Checked once, before any date is looked at. A manager reaches this function
     through the same page load an instructor does; the difference is here. */
  if (generationModeFor(input.viewerRole, "DAY") !== "GENERATE") {
    return { attempted: [], skipped: "not-permitted", peakConcurrency: 0 };
  }
  if (input.staleDates.length === 0) {
    return { attempted: [], skipped: "nothing-stale", peakConcurrency: 0 };
  }

  const queue = [...input.staleDates];
  const attempted: string[] = [];
  let inFlight = 0;
  let peak = 0;

  const worker = async () => {
    for (;;) {
      const date = queue.shift();
      if (date === undefined) return;
      attempted.push(date);
      inFlight += 1;
      peak = Math.max(peak, inFlight);
      try {
        await input.generate(date);
      } catch {
        /* A cell that fails to fill stays Pending. Rethrowing would abandon the
           rest of the queue over one day the viewer can still read raw. */
      } finally {
        inFlight -= 1;
      }
    }
  };

  await Promise.all(
    Array.from({ length: Math.min(MAX_CONCURRENT_GENERATIONS, queue.length) }, worker),
  );

  return { attempted, skipped: null, peakConcurrency: peak };
}
